services:
  - type: web
    name: fromagerie-invoice-app
    env: node
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: mongodb
    databaseName: fromagerie_invoices
    user: admin
